# Generated by Django 3.1.5 on 2021-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210122_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
