# Generated by Django 3.1.5 on 2021-01-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210126_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.TextField(),
        ),
    ]
